### ISSUE TITLE
Exercise: AQL search

### ISSUE THREAD

**Issue by sofusalbertsen** [praqma-training/artifactory-katas#10]
Some the things they can go through:

* Simple search: Get all files
* Use repository restriction (only these repositories)
* Search all the binaries from a given build
* Property search

**Comment by MichaelMadsen** [comment]
List all version of a given artifact that has been released, with the dates of deployment

**Comment by sofusalbertsen** [comment]
@bicschneider Now you have even more to AQL about ;)

**Comment by bicschneider** [comment]
* (?) Why do you download more than ones of each file?
`download_artifact $((RANDOM%10)) "/$MATURITY_1_REPO/acme/duck/1.0.0/duck-1.0.0.jpg" &>> $LOGFILE`
* (FIXED) I have made the download more security wise correct. `curl` downloads default to `stdout` which causes problem for terminals and `curl` actually exists with `exitcode > 0` . This is shown after I have set `set -e` in the `utils.sh`

**Comment by sofusalbertsen** [comment]
I'm simulating a usage, by downloading them.
And please pull the newest :)

**Comment by sofusalbertsen** [comment]
Don't polish the utils.sh, no one will see it, and it is there for setup only. Your energy is better spend on the exercises :)

**Comment by sofusalbertsen** [comment]
Ahh misunderstood your suggestions, sorry:
I want people to know how they can curl, that command is important, so the export is unfortunately necessary.

**Comment by bicschneider** [comment]
about the `export` how about storing it in a file that is then sourced..
