### ISSUE TITLE
Don't use .json-extension on files that aren't JSON in aql exercise

### ISSUE THREAD

**Issue by figaw** [praqma-training/artifactory-katas#65]
Using the .json file extension on files that aren't JSON is misleading and wrong.

It's not JSON and it doesn't work with the `jfrog`-cli (which otherwise accepts JSON.)

Proposal: rename aql-query files to `.aql` to conform to the `SQL` format of `.sql`. Artifactory proposes no guidelines for this. 

Could also be `.aql-query` but that opposes that SQL query files aren't called `.sql-query`. @sofusalbertsen?

**Comment by sofusalbertsen** [comment]
`.aql` seems like a sane thing to do :) Thanks for posting this
